config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'todos', to: 'posts#index'
get  'todos/list' 
get  'todos/new'
post 'todos',     to: 'todos#create'
get  'todos/:id', to: 'todos#show',  as: 'todo'
get  'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
patch 'todos/:id', to: 'todos#update'
delete 'todos/:id', to: 'todos#destroy', as: 'delete_todo'
get  'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
root 'todos#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all.order('id')
  end

  def new
    @todo = Todo.new
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to   root_path notice: "Se ha eliminado  el registro"
  end

  def complete
         @todo = Todo.find(params[:id])
         if@todo.update(completed: !@todo.completed)
               redirect_to   root_path, notice: "Se ha actualizado  el registro"
         else
             redirect_to edit_todo_path(@todo), notice: "No se actualizo registro"
         end
  end

  def list
        @todos = Todo.all
        @completado = @todos.select{ |valor|  valor.completed }
        @pendiente =  @todos.select{ |valor| !valor.completed  }
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
          redirect_to   root_path, notice: "Se ha actualizado  el registro"
    else
        redirect_to edit_todo_path(@todo), notice: "No se actualizo registro"
    end
  end

  def  show
     @todo = Todo.find(params[:id])
  end

  def edit
      @todo = Todo.find(params[:id])
  end

  def create
      todo = Todo.new(todo_params)
      if todo.completed.nil?
         todo.completed = 0
      end

      if todo.save
        redirect_to root_path, notice: "Se ha creado el registro"
      else
        redirect_to root_path, notice: "No se  ha creado el registro"
      end
    end

    private

    def todo_params
      params.require(:todo).permit(:description,:completed)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to 'Volver Index',  root_path, class:'navbar-brand' %>

          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to 'Lista de ToDo',  todos_list_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Creacion de ToDo',  todos_new_path, class:'nav-link' %>
              </li>
            </ul>
          </div>
        </nav>

    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<%= notice %>
<br class='mt-5'>
<div class=container>
<h1 class="text-center">MODIFICACION DE UN NUEVO ToDo</h1>
<br><br>
<br><br>
<%= form_with(model: @todo, local: true) do |f| %>
  <%= f.label :actividad %>  <%= f.text_field :description  %><br>
  <%= f.label :completado%>  <%= f.check_box :completed  %> <br>
  <%= f.submit :Modificar , class:'btn btn-primary'%>
  <%= link_to 'Volver Index',  root_path, class:'btn btn-primary' %>
<% end %>
</div>

app/views/todos/index.html.erb
<%= notice %>
<br class='mt-5'>

<h1 class="text-center">Lista de Actividades ToDo </h1>

<div class='container'>
<br><br>
    <%= link_to 'Crar un nuevo ToDo',  todos_new_path, class:'btn btn-primary' %>
<br><br>
</div>
<div class='container'>
  <div class="card-deck">
  <% @todos.each do |todo| %>
    <div class="card m-0 " style="width: 10rem;">
      <div class="card-block">
        <h5 class="card-title"><%= todo.description %></td></h5>
        <p class="card-text font-weight-bold"><%= ( todo.completed ? 'Actividad Completada': 'Sin Completar') %></p>
        <div class='text-center'>
        <%= link_to  ( todo.completed ? 'Desactivar': 'Completado') , complete_todo_path(todo), class:"btn btn-success  btn-xs m-1"%>
        <%= link_to 'Editar', edit_todo_path(todo) ,class:'btn btn-primary   btn-xs m-1'%>
        <%= link_to 'Ver', todo,class:'btn btn-primary  btn-xs m-1'%>
        <%= link_to 'Eliminar', delete_todo_path(todo), data: { confirm: "Seguro de Eliminar?"} , method: :delete, class:'btn  btn-xs btn-danger m-1' %>
      </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/todos/list.html.erb
<br class='mt-5'>

<div class=container>
<h1 class="text-center">LISTA DE ACTIVIDADES ToDo</h1>
</div>
<div class="container">
  <%= link_to 'Volver Index',  root_path, class:'btn btn-primary' %>
</div>
<br><br>
<div class="container">

  <div class="row">
    <div class="col">
      <h1 class="text-primary">PENDIENTES</h1>
      <% @pendiente.each do |todo| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= todo.description %></td></h5>
            <p class="card-text"><%= ( todo.completed ? 'Actividad Completada': 'Sin Completar') %></p>
          </div>
        </div>
      <% end %>

    </div>
    <div class="col">
      <h1 class="text-primary">COMPLETADOS</h1>
      <% @completado.each do |todo| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= todo.description %></td></h5>
            <p class="card-text"><%= ( todo.completed ? 'Actividad Completada': 'Sin Completar') %></p>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/todos/new.html.erb
<%= notice %>
<br class='mt-5'>
<div class=container>
<h1 class="text-center">CREACION DE UN NUEVO ToDo</h1>
<br><br>
<br><br>
<%= form_with(model: @todo, local: true) do |f| %>
  <%= f.label :actividad %>  <%= f.text_field :description  %><br>
  <%= f.submit :Crear , class:'btn btn-primary'%>
  <%= link_to 'Volver Index',  root_path, class:'btn btn-primary' %>
<% end %>
</div>

app/views/todos/show.html.erb
<br class='mt-5'>
<div class='container'>
<h1>Detalle</h1>
<table class="table table-striped">
<thead class="thead-dark">
  <tr>
      <th scope="col">DESCRIPCION</th>
      <th scope="col">ESTADO</th>
  </tr>
<thead>
<tbody>
  <tr>
    <td><%= @todo.description %></td>
    <td><%= ( @todo.completed ? 'Actividad Completada': 'Sin Completar') %></td>
  </tr>
</tbody>
</table>

<div class='text-center'>
<%= link_to 'Volver Index',  root_path, class:'btn btn-primary' %>
</div>
</div>